// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOGx1XEl11EwTeNBxnnAc16Mj--OtqQPs',
    appId: '1:1043887338084:web:92cb00ee9eed3511dd6571',
    messagingSenderId: '1043887338084',
    projectId: 'thanhsongarden-99850',
    authDomain: 'thanhsongarden-99850.firebaseapp.com',
    storageBucket: 'thanhsongarden-99850.appspot.com',
    measurementId: 'G-K0XP72CY8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEKQynG3p00oP6JeDloOGrHdVtFOq-vDY',
    appId: '1:1043887338084:android:6356729baeaa4b74dd6571',
    messagingSenderId: '1043887338084',
    projectId: 'thanhsongarden-99850',
    storageBucket: 'thanhsongarden-99850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVJCfzIdUwy1qaCz3xpbn74l6q8eGnOSc',
    appId: '1:1043887338084:ios:166fb73e533adbb4dd6571',
    messagingSenderId: '1043887338084',
    projectId: 'thanhsongarden-99850',
    storageBucket: 'thanhsongarden-99850.appspot.com',
    iosBundleId: 'com.example.thanhson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVJCfzIdUwy1qaCz3xpbn74l6q8eGnOSc',
    appId: '1:1043887338084:ios:db49f879930c98f6dd6571',
    messagingSenderId: '1043887338084',
    projectId: 'thanhsongarden-99850',
    storageBucket: 'thanhsongarden-99850.appspot.com',
    iosBundleId: 'com.example.thanhson.RunnerTests',
  );
}
